/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author Harshiprabhu
 */
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;
import java.awt.Color;
import java.sql.*;

public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    static String name;
    public Loginform() {
        
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        lUserId = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        pPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bCreateAccount = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Electricity Billing - Login page");
        setName("LoginFrame"); // NOI18N
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        lTitle.setText("Login Page");

        lUserId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lUserId.setText("Customer ID:");

        tfUserId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tfUserId.setNextFocusableComponent(lPassword);
        tfUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIdActionPerformed(evt);
            }
        });

        lPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lPassword.setText("Password: ");

        pPassword.setNextFocusableComponent(bLogin);

        bLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bClose.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bCreateAccount.setText("Create a New Account");
        bCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateAccountActionPerformed(evt);
            }
        });

        lMessage.setForeground(new java.awt.Color(255, 0, 0));
        lMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(bCreateAccount)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(lUserId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLogin)
                        .addGap(3, 3, 3)))
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfUserId)
                        .addComponent(pPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(pPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin)
                    .addComponent(bClose))
                .addGap(18, 18, 18)
                .addComponent(bCreateAccount)
                .addGap(63, 63, 63))
        );
        /*img1 = new JLabel(); //JLabel Creation
        img1.setIcon(new ImageIcon("electri3.jpg")); //Sets the image to be displayed as an icon
       //Dimension size = img1.getPreferredSize(); //Gets the size of the image
        img1.setSize(800,600);
        img1.setLocation(0,0);*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void tfUserIdActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        try{
            String userId = tfUserId.getText();
            String password = new String(pPassword.getPassword());
            lMessage.setForeground(Color.RED);
            
            if(userId.equals("")) lMessage.setText("ENTER CUSTOMER ID");
            else if(password.equals("")) lMessage.setText("ENTER PASSWORD");
            else{
            
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3308/consumer";
                String pass1=pPassword.getText();
                name=tfUserId.getText();
                Connection con = DriverManager.getConnection(url,"root", "1234");
                Statement s = con.createStatement();
                String query = String.format("select pass from signup where userId='"+name+"'");
                System.out.println(query);
                ResultSet rs = s.executeQuery(query);
                String pwd;
                if(!rs.next()) lMessage.setText("Account Not Found");
                else{
                    pwd = rs.getString(1);
                    if(!pwd.equals(pass1)) lMessage.setText("Incorrect Password");
                    else{
                        JOptionPane.showMessageDialog(this,"Login Successful");
                        lMessage.setForeground(Color.BLUE);
                        lMessage.setText("Logging in");
                        new Home().setVisible(true);
                        dispose();
                    }
                }
             
            } 
            
        }
        catch(ClassNotFoundException e){}
        catch(SQLIntegrityConstraintViolationException se){}
        catch(SQLException e){System.out.println(e);}
        
    }                                      

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        System.exit(0);
        
    }                                      

    private void bCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new CreateAccountFrame().setVisible(true);
        dispose();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bCreateAccount;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lUserId;
    private javax.swing.JPasswordField pPassword;
    private javax.swing.JTextField tfUserId;
    // End of variables declaration                   
}
